# Generated by Django 3.1.7 on 2021-03-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_description',
            new_name='work_descriptions',
        ),
    ]
