# Generated by Django 3.1.7 on 2021-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
